{% set name = "napari-deeplabcut" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_deeplabcut-{{ version }}.tar.gz
  sha256: 294e2c69bf8ef5d4567c414281c20c1a8d2c1f0473e7eb8f076448cedb51c0c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - dask-image
    - napari <0.5.0
    - numpy
    - pandas
    - python >=3.8
    - qtpy
    - scikit-image
    - pytables
    - pyyaml

test:
  imports:
    - napari_deeplabcut
  commands:
    - pip list
    # - pip check  # Can be uncommented when upstream requirements are updated/corrected
  requires:
    - pip

about:
  home: https://github.com/DeepLabCut/napari-deeplabcut
  summary: napari + DeepLabCut annotation tool
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeylau
    - goanpeca
    - jaimergp
