{% set name = "napari-deeplabcut" %}
{% set version = "0.2.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_deeplabcut-{{ version }}.tar.gz
  sha256: b590d09af7c94803d08686d42c600932371bdb23a85fdd6dbb8cf3b1d4385dba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - dask-core              #  Imported but not listed as requirement
    - dask-image
    - matplotlib-base >=3.3
    - napari <0.5.0
    - natsort
    - numpy
    - opencv
    - pandas
    - pytables               # Listed as requirement but not imported
    - python >=3.8
    - pyyaml
    - qtpy >=2.4
    - scikit-image

test:
  imports:
    - napari_deeplabcut
  commands:
    - pip list
    # - pip check  # Can be uncommented when upstream requirements are updated/corrected
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-deeplabcut
  summary: napari + DeepLabCut annotation tool
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/DeepLabCut/napari-deeplabcut

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jeylau
