{% set name = "napari-deeplabcut" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_deeplabcut-{{ version }}.tar.gz
  sha256: da35278f0bb6883943f2bb40e0d528dff120f3e1fb0ed0ae7fdb7c132c6a31ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - dask-core
    - dask-image
    - napari <0.5.0
    - numpy
    - opencv
    - pandas
    - python >=3.8
    - qtpy
    - scikit-image
    - pytables
    - pyyaml

test:
  imports:
    - napari_deeplabcut
  commands:
    - pip list
    # - pip check  # Can be uncommented when upstream requirements are updated/corrected
  requires:
    - pip

about:
  home: https://github.com/DeepLabCut/napari-deeplabcut
  summary: napari + DeepLabCut annotation tool
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeylau
    - goanpeca
    - jaimergp
